### ISSUE TITLE
Not possible to build demo

### ISSUE THREAD

**Issue by marvec** [belaban/TaskDistribution#1]
It is not possible to build the demo because
1) there is a wrong language level set in build.xml
2) jgroups.jar resources are not properly prepared and stored in conf directory
3) MANIFEST.MF is not created in the conf directory
4) resulting jar file does not contain any source code

Simply the ant build procedure is not working with the current project.
Ant 1.9.2, Ivy 2.4.0

**Comment by belaban** [comment]
I fixed this, 'ant run' should now do the job
