### ISSUE TITLE
Can I think executor building block is advanced version compared with this demo?

### ISSUE THREAD

**Issue by kitepad** [belaban/TaskDistribution#3]

**Comment by belaban** [comment]
The {{ExecutionService}} building block implement {{ExecutorService}}. It is more elaborate than TaskDistribution, but not very well maintained, I'm afraid... :-(

**Comment by kitepad** [comment]
Hi,

I found this message in jgroups manual :
STOMP clients can send messages to cluster members, and vice versa.

But my cluster member don’t receive any messages when I using STOMPConnecion connect to my cluster, only other stomp client receive message. Would you  give me some advices or tell me where to find samples? My scenario is :

  1.  Start 2 instance to form a cluster.
  2.  Create stomp client to connect to this cluster.
  3.  Send message to cluster

I expect 2 cluster members can receive message which send by client.

Thanks.

**Comment by belaban** [comment]
Do you have a code sample that I could try out? Bela Ban-------- Original Message --------Subject: Re: [belaban/TaskDistribution] Can I think executor building block is advanced version compared with this demo? (#3)From: kitepad To: belaban/TaskDistribution CC: Bela Ban ,State change Hi,



I found this message in jgroups manual :

STOMP clients can send messages to cluster members, and vice versa.



But my cluster member don’t receive any messages when I using STOMPConnecion connect to my cluster, only other stomp client receive message. Would you  give me some advices or tell me where to find samples? My scenario is :



  1.  Start 2 instance to form a cluster.

  2.  Create stomp client to connect to this cluster.

  3.  Send message to cluster



I expect 2 cluster members can receive message which send by client.



Thanks.
